# Generated by Django 5.0.4 on 2024-04-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("body", models.TextField(verbose_name="Содержимое")),
                (
                    "created_at",
                    models.DateField(auto_now=True, verbose_name="Дата создания"),
                ),
                (
                    "published",
                    models.BooleanField(default=True, verbose_name="Опубликован"),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "ordering": ("created_at",),
            },
        ),
    ]
