# Generated by Django 4.2.2 on 2024-04-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="new_images",
                verbose_name="изображение",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Счётчик просмотров"
            ),
        ),
    ]
