# Generated by Django 5.0.4 on 2024-04-20 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "surname",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Отчество"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Емейл"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Напишите уточняющую информацию",
                        max_length=300,
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "ordering": ("last_name", "first_name", "contact_email"),
            },
        ),
        migrations.CreateModel(
            name="MailAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_time",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата и время последней попытки",
                    ),
                ),
                (
                    "attempt_status",
                    models.CharField(
                        choices=[("Success", "Успешно"), ("Non-success", "Неуспешно")],
                        default="Success",
                        max_length=20,
                        verbose_name="Статус попытки",
                    ),
                ),
                (
                    "server_response",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ответ почтового сервера"
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка отправки рассылки",
                "verbose_name_plural": "Попытки отправки рассылки",
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_datetime_mailing",
                    models.DateField(
                        default=datetime.datetime(2024, 4, 20, 23, 8, 41, 491086),
                        verbose_name="Дата и время начала отправки рассылки",
                    ),
                ),
                (
                    "stop_datetime_mailing",
                    models.DateTimeField(
                        default=datetime.datetime.now,
                        verbose_name="Дата и время окончания отправки рассылки",
                    ),
                ),
                (
                    "mailing_period",
                    models.CharField(
                        choices=[
                            ("once", "1 раз"),
                            ("every_day", "Ежедневно"),
                            ("every_week", "Еженедельно"),
                            ("every_month", "Ежемесячно"),
                        ],
                        default="once",
                        max_length=25,
                        verbose_name="Периодичность рассылки",
                    ),
                ),
                (
                    "mailing_status",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("started", "Запущена"),
                            ("finished", "Завершена"),
                        ],
                        default="created",
                        max_length=25,
                        verbose_name="Статус выполнения рассылки",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Название рассылки",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Активность рассылки"
                    ),
                ),
                (
                    "created_date",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="Дата создания"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Без темы", max_length=100, verbose_name="Тема письма"
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True, null=True, verbose_name="Основное содержание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ("title",),
            },
        ),
    ]
