# Generated by Django 4.2.2 on 2024-04-23 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="start_datetime_mailing",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 23, 14, 20, 53, 971380),
                verbose_name="Дата и время начала отправки рассылки",
            ),
        ),
    ]
