# Generated by Django 5.0.4 on 2024-04-21 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="start_datetime_mailing",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 21, 22, 19, 41, 751570),
                verbose_name="Дата и время начала отправки рассылки",
            ),
        ),
    ]
