# Generated by Django 4.2.2 on 2024-04-23 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0002_alter_mailing_start_datetime_mailing"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailattempt",
            name="attempt_status",
            field=models.CharField(
                choices=[("Success", "Успешно"), ("Non-success", "Неуспешно")],
                default="Success",
                max_length=15,
                verbose_name="Статус попытки",
            ),
        ),
        migrations.AlterField(
            model_name="mailattempt",
            name="attempt_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время последней попытки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="mailing_period",
            field=models.CharField(
                choices=[
                    ("every_day", "Ежедневно"),
                    ("every_week", "Еженедельно"),
                    ("every_month", "Ежемесячно"),
                ],
                default="once",
                max_length=25,
                verbose_name="Периодичность рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start_datetime_mailing",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 23, 16, 6, 6, 267093),
                verbose_name="Дата и время начала отправки рассылки",
            ),
        ),
    ]
