# Generated by Django 4.2.2 on 2024-04-23 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0003_mailattempt_attempt_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="clients",
            field=models.ManyToManyField(
                related_name="client", to="mail.client", verbose_name="Клиенты рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start_datetime_mailing",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 23, 19, 45, 34, 162456),
                verbose_name="Дата и время начала отправки рассылки",
            ),
        ),
    ]
