# Generated by Django 5.0.4 on 2024-04-21 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0003_alter_mailing_start_datetime_mailing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="start_datetime_mailing",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 22, 0, 30, 46, 296463),
                verbose_name="Дата и время начала отправки рассылки",
            ),
        ),
    ]
