# Generated by Django 4.2.2 on 2024-04-23 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0004_alter_mailing_clients_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="start_datetime_mailing",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 23, 22, 56, 51, 706863),
                verbose_name="Дата и время начала отправки рассылки",
            ),
        ),
    ]
