# Generated by Django 4.2.2 on 2024-04-23 22:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0005_alter_mailing_start_datetime_mailing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="start_datetime_mailing",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 24, 1, 36, 5, 374680),
                verbose_name="Дата и время начала отправки рассылки",
            ),
        ),
    ]
