# Generated by Django 4.2.2 on 2024-04-25 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0006_alter_mailing_start_datetime_mailing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="start_datetime_mailing",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 25, 10, 17, 24, 496676),
                verbose_name="Дата и время начала отправки рассылки",
            ),
        ),
    ]
