# Generated by Django 4.2.2 on 2024-04-25 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0007_alter_mailing_start_datetime_mailing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailattempt",
            name="attempt_status",
            field=models.CharField(
                choices=[("Success", "Успешно"), ("No_success", "Неуспешно")],
                default="Success",
                max_length=15,
                verbose_name="Статус попытки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start_datetime_mailing",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 25, 12, 15, 31, 542632),
                verbose_name="Дата и время начала отправки рассылки",
            ),
        ),
    ]
