# Generated by Django 4.2.2 on 2024-04-25 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0008_alter_mailattempt_attempt_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="start_datetime_mailing",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 25, 13, 9, 19, 89353),
                verbose_name="Дата и время начала отправки рассылки",
            ),
        ),
    ]
